### ISSUE TITLE
Player cannot move in opposite direction of current direction without dying

### ISSUE THREAD

**Issue by Valdorous** [Valdorous/SnakeJs#2]
If player is going left and presses the right arrow the snake dies, should this not be blocked?
Not sure if bug, feature... Or unintentional rule?

**Comment by FalcoG** [comment]
Should be blocked in my opinion, keeping this will cause unnecessary deaths.

**Comment by Valdorous** [comment]
@FalcoG fixed in latest commit https://github.com/Valdorous/SnakeJs/commit/6747852090ff932712350ecbe8c9bb60a9aae98b
